### ISSUE TITLE
Webhook types for bank transfer

### ISSUE THREAD

**Issue by danlgz** [recurrente/recurrente-docs#2]
In the API Documentation (external link provided by this documentation) it says the bank transfer event types are `payment_intent.pending` `payment_intent.succeeded` `payment_intent.failed` just like the Credit Card events.

![image](https://user-images.githubusercontent.com/26347085/203858737-945e0cea-ad17-4c63-8e0a-3cecf45cf69e.png)

But in the event log are different

![image](https://user-images.githubusercontent.com/26347085/203858589-fb9c148d-c9d7-4065-85b9-2e02bfbd8f79.png)

**Comment by maxcodes** [comment]
Thanks for pointing this out @danlgz! I'll get this fixed by tomorrow.

**Comment by maxcodes** [comment]
<img width="890" alt="image" src="https://user-images.githubusercontent.com/6092334/203975921-d963454b-b041-46d8-a2aa-9699af5e4f8e.png">
Fixed!
